include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    require_trailing_commas: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
