name: bus_ticketing
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  collection: ^1.17.1
  dio: ^5.1.2
  either_dart: ^0.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  sizer: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
